# POST http://localhost:3000/api/wilder
# Content-Type: application/json

# {
#     "name": "Jane Doe"
# }

# GET http://localhost:3000/api/wilder

# DELETE http://localhost:3000/api/wilder/28

PUT http://localhost:3000/api/wilder/27
Content-Type: application/json

{
    "name": "Jane Doe"
}